version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=s3,elasticsearch,iam,cloudwatch,sts,es,ec2,kms,sns,ssm,lambda,sqs
      - DEBUG=${DEBUG- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test:
          - CMD
          - bash
          - -c
          - awslocal s3 ls
      interval: 5s
      timeout: 10s
      start_period: 10s
  tf-bucket:
    image: amazon/aws-cli:latest 
    command: --endpoint-url=http://localstack:4566 s3 mb s3://terraform-state
    environment:
        - AWS_ACCESS_KEY_ID=fake
        - AWS_SECRET_ACCESS_KEY=fake
        - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      localstack:
        condition: service_healthy
  healthcheck:
    image: amazon/aws-cli:latest 
    command: aws --endpoint-url=http://localhost:4566 s3api list-buckets
    environment:
        - AWS_ACCESS_KEY_ID=fake
        - AWS_SECRET_ACCESS_KEY=fake
        - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      localstack:
        condition: service_healthy
      tf-bucket:
        condition: service_completed_successfully
      